### ISSUE TITLE
dialer.DialContext undefined (type *websocket.Dialer has no field or method DialContext)

### ISSUE THREAD

**Issue by aonemd** [vulcand/oxy#166]
I get the following error whenever I'm trying to use the `forward` package: `vulcand/oxy/forward/fwd.go:347:33: dialer.DialContext undefined (type *websocket.Dialer has no field or method DialContext)`. I understand that the error occurs because the function `websocket.DefaultDialer.DialContext()` does not exist (anymore?) in [gorilla/websocket](https://github.com/gorilla/websocket) but I don't quite understand the code to fix it. If someone is willing to point out where to go from here, I'd really appreciate it.

**Comment by cognusion** [comment]
Gorilla needs freshening:
```go get -u github.com/gorilla/websocket```
