### ISSUE TITLE
adjust websocket loglevel for abnormal close

### ISSUE THREAD

**Issue by zyclonite** [vulcand/oxy#185]
#### current behavior
with more and more mobile clients, it happens quite often that the browser is closed and the underlying websocket connection gets not gracefully close. it happens as well for connection loss of the mobile device.
at the moment `vulcand/oxy/forward/websocket: Error when copying from client to backend...` is logged as error https://github.com/vulcand/oxy/blob/ba0780a8e6a6fca0a347021c959278f44b745cfa/forward/fwd.go#L471
i personally would switch the level to debug because this gets logged several times per second on larger sites

#### expected behavior
loglevel at `debug` or at least `info`

**Comment by zyclonite** [comment]
feel free to merge https://github.com/vulcand/oxy/pull/186

**Comment by ldez** [comment]
Considering refactoring #229, the specific code for WebSocket has been removed.
