### ISSUE TITLE
httpForwarder.serveWebSocket Uses global dialer

### ISSUE THREAD

**Issue by ckaznocha** [vulcand/oxy#199]
[`serveWebSocket`](https://github.com/vulcand/oxy/blob/master/forward/fwd.go#L331) uses the global [`websocket.DefaultDialer`](https://github.com/gorilla/websocket/blob/master/client.go#L130) to dial WebSocket connections. This would not be an issue except each call to `serveWebSocket` may modify [`websocket.DefaultDialer.TLSClientConfig`](https://github.com/vulcand/oxy/blob/master/forward/fwd.go#L342). This means there may be unpredictable behavior if an application has more than one forwarder serving WebSockets. This could potentially be the cause of #125 

I would also like to add an `optSetter` to modify the WebSocket Dialer the use of a global dialer is blocking that feature.

Happy to send a PR!

**Comment by ldez** [comment]
Considering refactoring #229, the specific code for WebSocket has been removed.
