### ISSUE TITLE
Replace logrus with minimal Logger interface

### ISSUE THREAD

**Issue by sylr** [vulcand/oxy#202]
It would be really useful if, instead of using logrus, oxy would rely on a minimal Logger interface such as:

```golang
type Logger interface {
	Debugf(string, ...interface{})
	Infof(string, ...interface{})
	Warnf(string, ...interface{})
	Errorf(string, ...interface{})
	Fatalf(string, ...interface{})
}
```

This will allow people to bring their own logger to oxy and therefor have oxy logs the same format as the software that includes it.

**Comment by ckaznocha** [comment]
Hi @sylr, without too much trouble you can use a different logger today. Create a logurs hook to wrap whatever logger you want to actually use. Pass a new logurs instance to oxy instrumented with your hook. Set the `logrus.Logger.Out` to `ioutil.Discard` if you don't want any output from logrus.

**Comment by StarpTech** [comment]
I think this issue hasn't been solved. I still see the logrus logger in the buffer package.

**Comment by ldez** [comment]
Are you sure? https://github.com/vulcand/oxy/tree/master/buffer

**Comment by StarpTech** [comment]
My issue. I didn't upgrade to v2.
