### ISSUE TITLE
Issue with the forward package

### ISSUE THREAD

**Issue by arkan** [vulcand/oxy#22]
Hi,
I'm trying to implement a reverse proxy on top of the `forward` and `roundrobin` packages.
It works, but not as expected. When I bench the service with [wrk](https://github.com/wg/wrk), it starts to slow down the requests' processing after a few seconds, and starts to display error messages:

`ERR: 2015/09/01 17:26:24.843441 Error forwarding to http://127.0.0.1:8082, err: dial tcp 127.0.0.1:8082: can't assign requested address`

I created a full example here which reproduces the issue: https://gist.github.com/Arkan/3f344293fd79560a96c4

Do you have any idea? 

Thanks

**Comment by emilevauge** [comment]
@Arkan, have you found a workaround? I'm getting the same issue:
the server starts to slow down the requests after some time, and shows `Error forwarding to http://172.17.0.3:80, err: dial tcp 172.17.0.3:80: i/o timeout `.

**Comment by lunemec** [comment]
This is dupliacte with #57. This issue was first, but the #57 has some proposed solutions. This should be closed as dupliacte and solved there.
