### ISSUE TITLE
Configure DefaultMaxRetryAttempts

### ISSUE THREAD

**Issue by ViviLearns2Code** [vulcand/oxy#233]
Hello, 

this line https://github.com/vulcand/oxy/blob/a0e9f7ff10402f5912abd9851659dec0988aa2c2/buffer/buffer.go#L204 effectively limits the number of attempts to 10, irrespective of the retry predicate specified. Am I missing something or is there a way to configure the max number of attempts?

Thanks! 😃

**Comment by ldez** [comment]
It seems to be [a "prehistorical" mistake](https://github.com/vulcand/oxy/commit/596a7a31026a5f122ca3832cf4a1daa75e23f98f#diff-2548f99ee58012641c03ff91e1197392d35714d856046bf647841b75bcc5c6e1R216-R217) :smile:, I fixed the problem with the predicate in #234.

**Comment by ViviLearns2Code** [comment]
@ldez hello again, I saw the PR with the fix was reverted - what was the reason behind it?

**Comment by ldez** [comment]
Hello, because it was a misunderstanding, the code is right.

**Comment by ViviLearns2Code** [comment]
@ldez does it mean that the number of retries should be limited to 10 by design?

**Comment by ViviLearns2Code** [comment]
@ldez hello, could you maybe elaborate on the misunderstanding? Is it indeed intended cap the number of retries at 10? Or can the number of retriews be higher as well (and I simply didn't see how to configure this)?
