### ISSUE TITLE
Unable to proxy requests

### ISSUE THREAD

**Issue by rafaeljesus** [vulcand/oxy#76]
Hi,

I am trying to proxy a request from `serviceA/login` to `serviceB/token`,

But I'm having 404 from the proxied service which is `serviceB/token`,

I noticed that `serviceA/login` successful proxies to `serviceB/login`, note the path `login` which is from `serviceA/login`, what I need is `serviceA/token?q=foo&z=bar` but I dunno how to exactly copy the request like I do with `httputil.ReverseProxy{Director: director}`

Here is the not working code using `oxy/forward`
```go
func (h *AuthProxyHandler) Proxy(w http.ResponseWriter, r *http.Request) {
  target, _ := url.Parse(h.tokenURL)
  targetQuery := target.RawQuery
  r.URL.Scheme = target.Scheme
  r.URL.Host = target.Host
  r.URL.Path = target.Path
  if targetQuery == "" || r.URL.RawQuery == "" {
    r.URL.RawQuery = targetQuery + r.URL.RawQuery
  } else {
    r.URL.RawQuery = targetQuery + "&" + r.URL.RawQuery
  }
  fwd, _ := forward.New()
  fwd.ServeHTTP(w, r)
}
```

here is the working version using `httputil.ReverseProxy`
```go
func (h *AuthProxyHandler) Proxy(w http.ResponseWriter, r *http.Request) {
	target, _ := url.Parse(h.tokenURL)
	targetQuery := target.RawQuery
	director := func(req *http.Request) {
		r.URL.Scheme = target.Scheme
		r.URL.Host = target.Host
		r.URL.Path = target.Path
		if targetQuery == "" || r.URL.RawQuery == "" {
			r.URL.RawQuery = targetQuery + r.URL.RawQuery
		} else {
			r.URL.RawQuery = targetQuery + "&" + r.URL.RawQuery
		}
	}
	p := &httputil.ReverseProxy{Director: director}
	p.ServeHTTP(w, r)
}
```

I've debugged the `response, err := f.roundTripper.RoundTrip(f.copyRequest(req, req.URL))` code noticed it does it in a different manner,

What am I missing?

Thanks

**Comment by bcotton** [comment]
FWIW, I was having this exact problem. tcptrace showed the original URL was being fetched against the target.

**Comment by ldez** [comment]
closed due to age.
