### ISSUE TITLE
No keepalives for streaming connections

### ISSUE THREAD

**Issue by sheerun** [vulcand/oxy#78]
Hey,

Because you "NewSingleHostReverseProxy(urlcpy)" in each connection in forwarder, the connections are never kept alive for streaming connections. This is an issue when backend server can't handle many open connections. For example when using docker for Mac: https://github.com/docker/for-mac/issues/815

Ideally you'd just create one reverse proxy per ip address, or create custom ReverseProxy with director that changes target url dynamically

**Comment by ldez** [comment]
Close due to age.
