### ISSUE TITLE
RedirectFallback does not preserve path

### ISSUE THREAD

**Issue by mgjv** [vulcand/oxy#88]
To be able to use the RedirectFallback in fallback.go for slightly more complex situations, it would be nice if it could be used to preserve the path of the current request on the redirect. For example, if the current request is

http://something/basepath/rest/of/path

and if redirect is set to 

http://somethingelse/otherbasepath

then I'd expect the redirect to go to

http://somethingelse/otherbasepath/rest/of/path

I'd like to add some code to either redirectfallback, or create a new fallback method, that can support this. Would a change like this be acceptable?

**Comment by klizhentas** [comment]
yes, go for it
